
controller_frequency: 10.0

TrajectoryPlannerROS:

  holonomic_robot: false

  yaw_goal_tolerance : 0.05

  xy_goal_tolerance: 0.05 # 0.1
  
  sim_time: 1.0

  meter_scoring: false

  pdist_scale: 0.6

#---------------------------------
  
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta: 3.5
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4
  escape_vel: -0.3
  
  pdist_scale: 0.6
  gdist_scale: 0.8
  heading_scoring_timestep: 1.2
  
  oscillation_reset_dist: 0.1
  
  latch_xy_goal_tolerance: false
  
  publish_cost_grid_pc: false
  
